import os
import requests
import time
from datetime import datetime

# Configurações
GITHUB_TOKEN = "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"
REPOS = [
    "Azure-Samples/acr-dotnet-manage-azure-container-registry",
    "Azure-Samples/acr-dotnet-manage-azure-container-registry-with-webhooks",
    "Azure-Samples/acr-tasks",
    "Azure-Samples/active-directory-b2c-dotnet-desktop",
    "Azure-Samples/active-directory-b2c-javascript-nodejs-webapi",
    "Azure-Samples/active-directory-b2c-xamarin-native",
    "Azure-Samples/active-directory-dotnet-native-aspnetcore-v2",
    "Azure-Samples/active-directory-dotnetcore-console-up-v2",
    "Azure-Samples/active-directory-verifiable-credentials-node",
    "Azure-Samples/agent-openai-python-prompty",
    "Azure-Samples/ai-rag-chat-evaluator",
    "Azure-Samples/aistudio-python-promptflow-sample",
    "Azure-Samples/aistudio-python-quickstart-sample",
    "aws-samples/amazon-bedrock-audio-summarizer",
    "aws-samples/amazon-bedrock-rag",
    "aws-samples/amazon-chime-sdk-meetings-with-amplify",
    "aws-samples/amazon-chime-sdk-pstn-audio-voice-focus",
    "aws-samples/amazon-cloudfront-access-logs-queries",
    "aws-samples/amazon-cloudfront-cache-graphql",
    "aws-samples/amazon-cloudfront-functions",
    "aws-samples/amazon-cloudfront-secure-static-site",
    "aws-samples/amazon-cloudwatch-auto-alarms",
    "aws-samples/amazon-codeguru-javascript-detectors",
    "aws-samples/amazon-codeguru-python-detectors",
    "aws-samples/amazon-connect-chat-translate",
    "aws-samples/amazon-devops-guru-connector-servicenow",
    "aws-samples/amazon-eks-inter-az-traffic-visibility",
    "aws-samples/amazon-elasticache-samples",
    "aws-samples/amazon-eventbridge-resource-policy-samples",
    "aws-samples/amazon-forecast-mlops-pipeline-cdk",
    "aws-samples/amazon-ivs-chat-web-demo",
    "aws-samples/amazon-ivs-clip-web-demo",
    "aws-samples/amazon-ivs-dvr-web-demo",
    "aws-samples/amazon-ivs-ecommerce-android-demo",
    "aws-samples/amazon-ivs-fitness-web-demo",
    "aws-samples/amazon-ivs-on-demand-android-demo",
    "aws-samples/amazon-ivs-player-android-sample",
    "aws-samples/amazon-ivs-player-web-sample",
    "aws-samples/amazon-ivs-real-time-streaming-android-samples",
    "aws-samples/amazon-kendra-langchain-extensions",
    "aws-samples/amazon-kinesis-analytics-beam-taxi-consumer",
    "aws-samples/amazon-kinesis-analytics-streaming-etl",
    "aws-samples/amazon-kinesis-data-analytics-flink-benchmarking-utility",
    "aws-samples/amazon-kinesis-data-analytics-snapshot-manager-for-flink",
    "aws-samples/amazon-location-service-pettracker-demo",
    "aws-samples/amazon-lookout-for-vision",
    "aws-samples/amazon-lookout-for-vision-demo",
    "aws-samples/amazon-rekognition-custom-labels-demo",
    "aws-samples/amazon-rekognition-engagement-meter",
    "aws-samples/amazon-rekognition-ppe",
    "aws-samples/amazon-rekognition-serverless-large-scale-image-and-video-processing",
    "aws-samples/amazon-rekognition-virtual-proctor",
    "aws-samples/amazon-s3-multipart-upload-transfer-acceleration",
    "aws-samples/amazon-s3-resumable-upload",
    "aws-samples/amazon-sagemaker-amazon-routing-challenge-sol",
    "aws-samples/amazon-sagemaker-endpoint-deployment-of-siamese-network-with-torchserve",
    "aws-samples/amazon-sagemaker-mlflow-fargate",
    "aws-samples/amazon-translate-pdf",
    "aws-samples/amazon-workspaces-portal-sample",
    "googlesamples/android-custom-lint-rules",
    "Azure-Samples/aoai-net-starterkit",
    "Azure-Samples/api-management-schema-import",
    "Azure-Samples/app-service-dotnet-access-key-vault-by-msi-for-web-apps",
    "Azure-Samples/app-service-dotnet-configure-deployment-sources-for-functions",
    "Azure-Samples/app-service-dotnet-configure-deployment-sources-for-web-apps",
    "Azure-Samples/app-service-dotnet-configure-deployment-sources-for-web-apps-async",
    "Azure-Samples/app-service-dotnet-configure-deployment-sources-for-web-apps-on-linux",
    "Azure-Samples/app-service-dotnet-deploy-image-from-acr-to-linux",
    "Azure-Samples/app-service-dotnet-manage-authentication-for-functions",
    "Azure-Samples/app-service-dotnet-manage-authentication-for-web-apps",
    "Azure-Samples/app-service-dotnet-manage-data-connections-for-web-apps",
    "Azure-Samples/app-service-dotnet-manage-data-connections-for-web-apps-on-linux",
    "Azure-Samples/app-service-dotnet-manage-functions",
    "Azure-Samples/app-service-dotnet-manage-functions-with-custom-domains",
    "Azure-Samples/app-service-dotnet-manage-logs-for-function-apps",
    "Azure-Samples/app-service-dotnet-manage-staging-and-production-slots-for-web-apps",
    "Azure-Samples/app-service-dotnet-manage-storage-connections-for-web-apps",
    "Azure-Samples/app-service-dotnet-manage-storage-connections-for-web-apps-on-linux",
    "Azure-Samples/app-service-dotnet-manage-web-apps",
    "Azure-Samples/app-service-dotnet-manage-web-apps-on-linux",
    "Azure-Samples/app-service-dotnet-manage-web-apps-on-linux-with-custom-domains",
    "Azure-Samples/app-service-dotnet-manage-web-apps-with-custom-domains",
    "Azure-Samples/app-service-dotnet-scale-web-apps",
    "Azure-Samples/app-service-dotnet-scale-web-apps-on-linux",
    "Azure-Samples/app-service-language-detector",
    "aws-samples/appfabric-sample-log-generator",
    "Azure-Samples/ApplicationInsights-Java-Samples",
    "aws-samples/appmod-partners-serverless",
    "Azure-Samples/ARGUS",
    "Azure-Samples/ASA-Samples-Restful-Application",
    "aws-samples/avp-petstore-sample",
    "aws-samples/aws-amplify-example-recipe-app-react-native",
    "aws-samples/aws-analytics-genai-llm-workshop",
    "aws-samples/aws-appsync-resolver-samples",
    "aws-samples/aws-athena-udfs-textanalytics",
    "aws-samples/aws-auto-inventory",
    "aws-samples/aws-cdk-emr-s3-trigger",
    "aws-samples/aws-codeguru-profiler-python-demo-application",
    "aws-samples/aws-codepipeline-bitbucket-integration",
    "aws-samples/aws-cognito-java-desktop-app",
    "aws-samples/aws-control-tower-guardduty-enabler",
    "aws-samples/aws-control-tower-securityhub-enabler",
    "aws-samples/aws-dataexchange-api-samples",
    "aws-samples/aws-decoupled-serverless-scheduler",
    "aws-samples/aws-eks-crac",
    "aws-samples/aws-health-events-insight",
    "aws-samples/aws-iot-robot-connectivity-samples-ros2",
    "aws-samples/aws-lambda-java-workshop",
    "aws-samples/aws-management-and-governance-samples",
    "aws-samples/aws-marketplace-api-samples",
    "aws-samples/aws-marketplace-serverless-saas-integration",
    "aws-samples/aws-medialive-channel-orchestrator",
    "aws-samples/aws-mlflow-sagemaker-cdk",
    "aws-samples/aws-modernization-with-snyk-security",
    "aws-samples/aws-multi-region-bc-dr-workshop",
    "aws-samples/aws-nitro-enclave-blockchain-wallet",
    "aws-samples/aws-nitro-enclaves-workshop",
    "aws-samples/aws-panorama-samples",
    "aws-samples/aws-reinvent-2023-code-talk-assets",
    "aws-samples/aws-resilience-hub-tools",
    "aws-samples/aws-sam-jenkins-pipeline-tutorial",
    "aws-samples/aws-sdk-js-tests",
    "aws-samples/aws-serverless-developer-experience-workshop-dotnet",
    "aws-samples/aws-serverless-developer-experience-workshop-java",
    "aws-samples/aws-serverless-security-workshop",
    "aws-samples/aws-serverless-workshop-innovator-island",
    "aws-samples/aws-step-functions-progress-tracking",
    "aws-samples/aws-virtual-participant-framework-for-rtc",
    "aws-samples/aws-waf-ops-dashboards",
    "aws-samples/awsome-inference",
    "Azure-Samples/azure-cafe",
    "Azure-Samples/azure-cosmos-db-python-getting-started",
    "Azure-Samples/azure-edge-extensions-polyglotnotebook-aio",
    "Azure-Samples/azure-edge-extensions-retrieval-augmented-generation",
    "Azure-Samples/azure-functions-samples-java",
    "Azure-Samples/azure-government-openai-access",
    "Azure-Samples/azure-load-testing-samples",
    "Azure-Samples/azure-openai-reverse-proxy",
    "Azure-Samples/azure-openai-terraform-deployment-sample",
    "Azure-Samples/azure-samples-python-management",
    "Azure-Samples/azure-search-dotnet-scale",
    "Azure-Samples/azure-search-java-samples",
    "Azure-Samples/azure-search-python-samples",
    "Azure-Samples/azure-service-operator-samples",
    "Azure-Samples/azure-spring-data-cosmos-java-sql-api-samples",
    "Azure-Samples/azure-sql-binding-func-dotnet-todo",
    "Azure-Samples/azure-sql-db-dotnet-rest-api",
    "Azure-Samples/azure-sql-db-fullstack-serverless-kickstart",
    "Azure-Samples/azure-sql-db-fusioncache",
    "Azure-Samples/azure-sql-db-sync-api-change-tracking",
    "Azure-Samples/azure-sql-db-todo-backend-func-node",
    "Azure-Samples/azure-sql-db-who-am-i",
    "Azure-Samples/azure-sql-functions-geocode",
    "aws-samples/bedrock-access-gateway",
    "Azure-Samples/build-your-first-orleans-app-aspnetcore",
    "Azure-Samples/cassandra-mi-client-configurator",
    "aws-samples/cdk-amazon-mwaa-cicd",
    "Azure-Samples/cdn-dotnet-manage-cdn",
    "aws-samples/clickstream-consumer-for-apache-kafka",
    "aws-samples/clickstream-producer-for-apache-kafka",
    "Azure-Samples/cognitive-services-python-sdk-samples",
    "Azure-Samples/communication-services-android-calling-hero",
    "Azure-Samples/communication-services-python-quickstarts",
    "Azure-Samples/communication-services-ui-library-maui",
    "Azure-Samples/communication-services-ui-library-xamarin",
    "Azure-Samples/compute-dotnet-manage-user-assigned-msi-enabled-virtual-machine",
    "Azure-Samples/compute-dotnet-manage-vm-async",
    "Azure-Samples/container-apps-dynamic-sessions-samples",
    "Azure-Samples/cosmos-db-nosql-dotnet-samples",
    "Azure-Samples/cosmos-db-nosql-python-samples",
    "Azure-Samples/cosmos-dotnet-core-getting-started",
    "Azure-Samples/cosmosdb-dotnet-create-cosmosdb-and-get-mongodb-connection-string",
    "aws-samples/cost-effective-aws-deployment-of-comfyui",
    "aws-samples/custom-web-experience-with-amazon-q-business",
    "Azure-Samples/data-box-samples",
    "aws-samples/data-engineering-for-aws-immersion-day",
    "Azure-Samples/digital-twins-docs-code",
    "Azure-Samples/digital-twins-iothub-integration",
    "Azure-Samples/dns-dotnet-host-and-manage-your-domains",
    "aws-samples/drs-malware-scan",
    "Azure-Samples/durablefunctions-apiscraping-dotnet",
    "Azure-Samples/e2e-dotnetcore-function-sendemail",
    "aws-samples/edge_diffusion_on_eks",
    "aws-samples/eks-multi-cluster-gitops",
    "aws-samples/eks-workshop-developers",
    "aws-samples/engineering-quickstarts-for-serverless-and-container-applications",
    "Azure-Samples/eventhub-dotnet-manage-event-hub",
    "Azure-Samples/eventhub-dotnet-manage-event-hub-events",
    "Azure-Samples/eventhub-dotnet-manage-event-hub-geo-disaster-recovery",
    "aws-samples/fedramp-integrated-inventory-workbook",
    "spring-cloud-samples/feign-eureka",
    "Azure-Samples/flask-app-on-azure-functions",
    "Azure-Samples/functions-docs-csharp",
    "Azure-Samples/functions-docs-javascript",
    "aws-samples/graceful-shutdown-with-aws-lambda",
    "aws-samples/graviton-workshop",
    "spring-guides/gs-accessing-data-jpa",
    "spring-guides/gs-accessing-data-mongodb",
    "spring-guides/gs-accessing-data-mysql",
    "spring-guides/gs-accessing-data-neo4j",
    "spring-guides/gs-accessing-data-r2dbc",
    "spring-guides/gs-accessing-data-rest",
    "spring-guides/gs-accessing-mongodb-data-rest",
    "spring-guides/gs-accessing-neo4j-data-rest",
    "spring-guides/gs-accessing-vault",
    "spring-guides/gs-actuator-service",
    "spring-guides/gs-async-method",
    "spring-guides/gs-authenticating-ldap",
    "spring-guides/gs-batch-processing",
    "spring-guides/gs-caching",
    "spring-guides/gs-centralized-configuration",
    "spring-guides/gs-cloud-circuit-breaker",
    "spring-guides/gs-consuming-rest",
    "spring-guides/gs-consuming-web-service",
    "spring-guides/gs-contract-rest",
    "spring-guides/gs-crud-with-vaadin",
    "spring-guides/gs-gateway",
    "spring-guides/gs-graphql-server",
    "spring-guides/gs-handling-form-submission",
    "spring-guides/gs-integration",
    "spring-guides/gs-managing-transactions",
    "spring-guides/gs-messaging-jms",
    "spring-guides/gs-messaging-rabbitmq",
    "spring-guides/gs-messaging-redis",
    "spring-guides/gs-messaging-stomp-websocket",
    "spring-guides/gs-multi-module",
    "spring-guides/gs-producing-web-service",
    "spring-guides/gs-reactive-rest-service",
    "spring-guides/gs-relational-data-access",
    "spring-guides/gs-rest-hateoas",
    "spring-guides/gs-rest-service",
    "spring-guides/gs-rest-service-cors",
    "spring-guides/gs-scheduling-tasks",
    "spring-guides/gs-securing-web",
    "spring-guides/gs-service-registration-and-discovery",
    "spring-guides/gs-serving-web-content",
    "spring-guides/gs-spring-boot",
    "spring-guides/gs-spring-boot-docker",
    "spring-guides/gs-spring-cloud-loadbalancer",
    "spring-guides/gs-spring-cloud-stream",
    "spring-guides/gs-spring-data-reactive-redis",
    "spring-guides/gs-tanzu-observability",
    "spring-guides/gs-testing-restdocs",
    "spring-guides/gs-testing-web",
    "spring-guides/gs-uploading-files",
    "spring-guides/gs-validating-form-input",
    "spring-guides/gs-vault-config",
    "aws-samples/http-requests-mirroring",
    "Azure-Samples/http-trigger-azure-function-premium-plan",
    "Azure-Samples/Hybrid-CSharp-Samples",
    "Azure-Samples/Hybrid-Golang-Samples",
    "Azure-Samples/Hybrid-Python-Samples",
    "aws-samples/integration-sample-lambda-msk",
    "Azure-Samples/iot-reliable-edge-relay",
    "Azure-Samples/iothub-to-azure-maps-geofencing",
    "Azure-Samples/java-native-telemetry",
    "aws-samples/jp-prototyping-blog",
    "Azure-Samples/js-e2e-express-server",
    "Azure-Samples/js-e2e-web-app-easy-auth-app-to-app",
    "Azure-Samples/key-vault-dotnet-manage-key-vaults",
    "aws-samples/lake-formation-permissions-sync",
    "aws-samples/lambda-extensions-workshop",
    "aws-samples/lambdaedge-openidconnect-samples",
    "Azure-Samples/llmops-gha-demo",
    "Azure-Samples/managed-disk-dotnet-convert-existing-virtual-machines-to-use-managed-disks",
    "Azure-Samples/managed-disk-dotnet-create-virtual-machine-using-custom-image",
    "Azure-Samples/managed-disk-dotnet-create-virtual-machine-using-custom-image-from-VHD",
    "aws-samples/migration-effort-estimator",
    "Azure-Samples/MipSDK-File-Java-Basic",
    "Azure-Samples/MipSDK-Protection-Dotnet-Quickstart",
    "Azure-Samples/MLOpsManufacturing",
    "Azure-Samples/monitor-dotnet-activitylog-alerts-on-security-breach-or-risk",
    "Azure-Samples/monitor-dotnet-autoscale-based-on-performance",
    "Azure-Samples/monitor-dotnet-metric-alerts-on-critical-performance",
    "Azure-Samples/ms-identity-android-java",
    "Azure-Samples/ms-identity-android-kotlin",
    "Azure-Samples/ms-identity-aspnet-daemon-webapp",
    "Azure-Samples/ms-identity-ciam-browser-delegated-android-sample",
    "Azure-Samples/ms-identity-ciam-native-auth-android-sample",
    "Azure-Samples/ms-identity-docs-code-dotnet",
    "Azure-Samples/ms-identity-docs-code-java",
    "Azure-Samples/ms-identity-docs-code-javascript",
    "Azure-Samples/ms-identity-docs-code-python",
    "Azure-Samples/ms-identity-dotnetcore-daemon-graph-cae",
    "Azure-Samples/ms-identity-node",
    "Azure-Samples/ms-identity-python-webapp-django",
    "Azure-Samples/msal-managed-identity",
    "Azure-Samples/msdocs-app-service-sqldb-dotnetcore",
    "Azure-Samples/msdocs-fastapi-postgres-codespace",
    "Azure-Samples/msdocs-python-django-azure-container-apps",
    "Azure-Samples/msdocs-python-django-webapp-quickstart",
    "aws-samples/msk-config-providers",
    "Azure-Samples/network-dotnet-create-simple-internet-facing-load-balancer",
    "Azure-Samples/network-dotnet-manage-internal-load-balancers",
    "Azure-Samples/network-dotnet-manage-internet-facing-load-balancers",
    "Azure-Samples/network-dotnet-manage-ip-address",
    "Azure-Samples/network-dotnet-manage-network-interface",
    "Azure-Samples/network-dotnet-manage-network-peering",
    "Azure-Samples/network-dotnet-manage-network-security-group",
    "Azure-Samples/network-dotnet-manage-virtual-network",
    "Azure-Samples/network-dotnet-manage-virtual-network-async",
    "Azure-Samples/network-dotnet-manage-virtual-network-to-virtual-network-vpn-connection",
    "Azure-Samples/network-dotnet-manage-virtual-network-with-site-to-site-vpn-connection",
    "aws-samples/nft-access-control-lambda-authorizer",
    "aws-samples/observability-with-amazon-opensearch",
    "Azure-Samples/open-liberty-on-aks",
    "Azure-Samples/Orleans-Cluster-on-Azure-App-Service",
    "aws-samples/pgp-decryption-for-transfer-family",
    "Azure-Samples/podcast-synopsis-generation-openai",
    "Azure-Samples/pubsub-dapr-aks-java",
    "aws-samples/pyflink-getting-started",
    "aws-samples/python-data-science-template",
    "aws-samples/qnabot-on-aws-plugin-samples",
    "Azure-Samples/quarkus-azure",
    "Azure-Samples/quote-of-the-day-dotnet",
    "aws-samples/reactive-refarch-cloudformation",
    "aws-samples/rekognition-video-people-blurring-cdk",
    "Azure-Samples/resources-dotnet-deploy-using-arm-template-with-progress",
    "aws-samples/saga-orchestration-netcore-blog",
    "aws-samples/sagemaker-studio-apps-lifecycle-config-examples",
    "aws-samples/sam-accelerate-nested-stacks-demo",
    "aws-samples/sample-python-helper-aws-appconfig",
    "spring-cloud-samples/sc-contract-car-rental",
    "Azure-Samples/search-dotnet-getting-started",
    "aws-samples/secure-pipelines-in-aws-workshop",
    "Azure-Samples/secure-tunneling-azure-relay",
    "aws-samples/serverless-httpdns",
    "aws-samples/serverless-java-frameworks-samples",
    "aws-samples/serverless-store-finder",
    "aws-samples/simple-websockets-chat-app",
    "spring-cloud-samples/sleuth-documentation-apps",
    "spring-cloud-samples/sleuth-issues",
    "aws-samples/spark-on-aws-lambda",
    "Azure-Samples/spring-chatgpt-sample",
    "aws-samples/streamlit-application-deployment-on-aws",
    "aws-samples/support-insights-with-amazon-q",
    "spring-cloud-samples/the-legacy-app",
    "Azure-Samples/traffic-manager-dotnet-manage-profiles",
    "spring-guides/tut-rest",
    "spring-guides/tut-spring-boot-kotlin",
    "Azure-Samples/vercel-nextjs-app-azure-db-mysql",
    "aws-samples/voice-enabled-patient-diary",
    "Azure-Samples/workshop-migrate-jboss-on-app-service"
]
SNAPSHOTS_PATH = "C:/Users/latinha/Desktop/Metodologia - Mestrado/Datasets/Snapshots"
HEADERS = {
    "Accept": "application/vnd.github+json",
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "X-GitHub-Api-Version": "2022-11-28"
}

def get_releases_by_year(repo):
    url = f"https://api.github.com/repos/{repo}/releases"
    response = requests.get(url, headers=HEADERS)
    
    if response.status_code == 200:
        releases = response.json()
        releases_by_year = {}
        
        for release in releases:
            created_at = release['created_at']
            release_year = datetime.strptime(created_at, '%Y-%m-%dT%H:%M:%SZ').year
            
            # Armazena apenas uma release por ano
            if release_year not in releases_by_year:
                releases_by_year[release_year] = release

        return releases_by_year
    else:
        print(f"Erro ao buscar releases de {repo}: {response.status_code}")
        return {}

def create_snapshots():
    for repo in REPOS:
        repo_name = repo.split('/')[-1]
        releases_by_year = get_releases_by_year(repo)
        
        for year, release in releases_by_year.items():
            release_tag = release['tag_name']
            release_dir = os.path.join(SNAPSHOTS_PATH, repo_name, str(year))
            
            os.makedirs(release_dir, exist_ok=True)
            
            # Formatação completa da URL
            full_repo_url = f"https://github.com/{repo}"
            print(f"Clonando {repo_name} - Ano: {year}, Release: {release_tag}...")
            os.system(f'git clone -b "{release_tag}" {full_repo_url}.git "{release_dir}"')
            print(f"Snapshot criado em: {release_dir}")

            # Aguarda um momento para evitar sobrecarga na API
            time.sleep(2)

create_snapshots()
